id: I2FF3FAE4
legacy_id: P009294
ocr_import_info:
  bdrc_scan_id: W1KG15935
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T08:08:12'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T08:26:26.335943+00:00'
last_modified: 2022-08-31 16:27:00.200393
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG15935
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG15935
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བསྟན་བཅོས་མངོན་པར་རྟོགས་པའི་རྒྱན་གྱི་རྩ་བ་དང་། དེའི་འགྲེལ་པ་དོན་གསལ་དང་བཅས་པའི་རྣམ་བཤད་སྙིང་པོའི་རྒྱན།
  author: སེངྒེ་བཟང་པོ།
statistics:
  ocr_word_mean_confidence_index: 0.8265981249365014
  ocr_word_median_confidence_index: 0.9700000286102295
quality: null
bases:
  I1KG15942:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG15942
      total_pages: 594
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG15942.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8397723767481892
    legacy_id: v001
  I1KG15943:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG15943
      total_pages: 510
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG15943.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8114832538695457
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
