id: P009294
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG15935
  title: བསྟན་བཅོས་མངོན་པར་རྟོགས་པའི་རྒྱན་གྱི་རྩ་བ་དང་། དེའི་འགྲེལ་པ་དོན་གསལ་དང་བཅས་པའི་རྣམ་བཤད་སྙིང་པོའི་རྒྱན།
  author: ''
  volumes: {}
